_wandb:
    value:
        cli_version: 0.26.1
        e:
            8p0mzoixh9olibfj6e9hsq951f6buzb2:
                args:
                    - --curvton_data_path
                    - /iopsstor/scratch/cscs/dbartaula/human_gen/dataset_v3_backup/dataset_ultimate_stratified_type
                    - --batch_size
                    - "4"
                    - --image_size
                    - "0"
                    - --num_workers
                    - "16"
                    - --max_steps
                    - "28000"
                    - --wandb_project
                    - Stable_diffusion
                    - --save_interval
                    - "1000"
                    - --image_log_interval
                    - "500"
                    - --output_dir
                    - /iopsstor/scratch/cscs/dbartaula/experiments_assets
                    - --run_name
                    - Stable_diffusion_train_ootdiffusion
                codePath: cross-architecture/OOTDiffusion/train_ootdiffusion_local.py
                codePathLocal: cross-architecture/OOTDiffusion/train_ootdiffusion_local.py
                cpu_count: 288
                cpu_count_logical: 288
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "255795462144"
                        used: "5692784640"
                email: 078bct.anandi@gmail.com
                executable: /iopsstor/scratch/cscs/dbartaula/miniforge3/envs/torch28_env_new/bin/python3.11
                git:
                    commit: 49b07805e986240f9e8529f21ce222595df261fa
                    remote: https://github.com/DipanBartaula/StableDiffusionExperimentss.git
                gpu: NVIDIA GH200 120GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-e57a7b79-ed5a-03a7-1db8-a1e4ec50102d
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-c823040c-3bde-59f4-1d82-5a8c61b15286
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-06f87069-a4a3-2ca5-7ca0-b6d322fc6d6b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-9fb0197a-89cc-78f9-9c6d-b36377ee9bad
                host: nid006210
                memory:
                    total: "919612817408"
                os: Linux-6.4.0-150600.23.47_15.0.10-cray_shasta_c_64k-aarch64-with-glibc2.38
                program: /iopsstor/scratch/cscs/dbartaula/StableDiffusionExperimentss/cross-architecture/OOTDiffusion/train_ootdiffusion_local.py
                python: CPython 3.11.15
                root: /iopsstor/scratch/cscs/dbartaula/StableDiffusionExperimentss
                slurm:
                    cluster_name: clariden
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    cpu_bind_list: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "288"
                    distribution: cyclic
                    gpus_on_node: "4"
                    gtids: "0"
                    job_account: a168
                    job_cpus_per_node: "288"
                    job_end_time: "1777903474"
                    job_gid: "1008"
                    job_gpus: 0,1,2,3
                    job_id: "2026322"
                    job_name: ootd
                    job_nodelist: nid006210
                    job_num_nodes: "1"
                    job_partition: normal
                    job_qos: normal
                    job_start_time: "1777867474"
                    job_uid: "1370"
                    job_user: dbartaula
                    jobid: "2026322"
                    launch_node_ipaddr: 172.28.27.72
                    localid: "0"
                    mem_per_node: "460800"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: nid006210
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    srun_comm_host: 172.28.27.72
                    srun_comm_port: "42871"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "42871"
                    step_nodelist: nid006210
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 29066-29067
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /iopsstor/scratch/cscs/dbartaula/StableDiffusionExperimentss/train_runs
                    submit_host: clariden-ln002
                    task_pid: "148928"
                    tasks_per_node: "1"
                    time_format: relative
                    topology_addr: global.group24.nid006210
                    topology_addr_pattern: switch.switch.node
                    umask: "0022"
                startedAt: "2026-05-04T04:05:29.243087Z"
                writerId: 8p0mzoixh9olibfj6e9hsq951f6buzb2
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 83
                - 98
            "3":
                - 13
                - 16
                - 41
            "4": 3.11.15
            "5": 0.26.1
            "6": 5.5.4
            "12": 0.26.1
            "13": linux-aarch64
batch_size:
    value: 4
category:
    value: all
curvton_data_path:
    value: /iopsstor/scratch/cscs/dbartaula/human_gen/dataset_v3_backup/dataset_ultimate_stratified_type
difficulty:
    value: all
disable_wandb:
    value: false
gender:
    value: all
image_log_interval:
    value: 500
image_size:
    value: 0
log_interval:
    value: 10
lr:
    value: 1e-05
max_steps:
    value: 28000
model_name:
    value: runwayml/stable-diffusion-v1-5
num_inference_steps:
    value: 30
num_workers:
    value: 16
outfitting_dropout:
    value: 0.1
output_dir:
    value: /iopsstor/scratch/cscs/dbartaula/experiments_assets
resume:
    value: null
run_name:
    value: Stable_diffusion_train_ootdiffusion
save_interval:
    value: 1000
wandb_project:
    value: Stable_diffusion
